In [1]:
# standard python modules for numerical and scientific computing
import scipy as sp
import scipy.spatial as spatial
import numpy as np

# 3D mesh visualization
import meshplot as mp

# python bindings for libigl, a 3D geometry processing library
# see https://libigl.github.io/libigl-python-bindings/tutorials/
import igl

import os
os.chdir("/home/jovyan/")
root_folder = os.getcwd()

In [2]:
# load 3D object
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data", "cow.off"))

# meshplot tutorial see https://skoch9.github.io/meshplot/tutorial/
p = mp.plot(v, c=np.tile([1, 0, 0], (v.shape[0],1)), shading={"point_size":0.07}, return_plot=True)

# make a rotated copy
rot = spatial.transform.Rotation.from_euler('y', 45, degrees=True)
v_rot = rot.apply(v)
#p.add_points(v_rot, c=np.tile([0, 1, 0],(v.shape[0],1)), shading={"point_size":0.07})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0062334…

### Assignment: Recover the Relative Rotation between the Two Point-clouds

Use the method described in the class material using the SVD. Apply the inverse of the recovered rotation to the rotated point cloud and display it together with the original. They should perfectly overlap.

The following numpy functions will be useful: `mean`, `matmul`, `transpose`, `linalg.svd`. From `scipy.spatial`, the class `transform.Rotation` will be useful. 

In [3]:
# your code here
print(v)
prods = list()
for i in range(len(v)):
    prod = np.outer(v_rot[i], v[i])
    prods.append(prod)
H = np.sum(prods, axis=0)
(u, _, vh) = np.linalg.svd(H)
X = np.transpose(u*vh)
print(np.linalg.det(X))
rot_inv = spatial.transform.Rotation.from_matrix(X)
v_new = rot_inv.apply(v_rot)
print(v_new.shape)
p.add_points(v_new, c=np.tile([0, 0, 1],(v.shape[0],1)), shading={"point_size":0.07})

[[ 0.151632 -0.043319 -0.08824 ]
 [ 0.163424 -0.033934 -0.08411 ]
 [ 0.163118 -0.053632 -0.080509]
 ...
 [-0.496861 -0.151519  0.001731]
 [-0.434551 -0.032299 -0.003589]
 [-0.416893  0.220802  0.      ]]
0.36299030741935767
(2762, 3)


1