# Differential Geometry on Meshes with `libigl`

These examples are from the [tutorial for libigl python bindings](https://libigl.github.io/libigl-python-bindings/tutorials). Read through Chapter 1 in the tutorial and go through the code here. At the end of this notebook there is a small assignment to solve for the learning check.

In [1]:
import igl
import scipy as sp
import numpy as np
import meshplot as mp

import os

os.chdir("/home/jovyan/")
root_folder = os.getcwd()

In [2]:
V = np.array([
    [0., 0, 0],
    [1, 0, 0],
    [1, 1, 1],
    [2, 1, 0]
])

F = np.array([
    [0, 1, 2],
    [1, 3, 2]
])

mp.plot(V, F)

print("Mesh adjacency matrix:\n", igl.adjacency_matrix(F).todense())

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(1.0, 0.5,…

Mesh adjacency matrix:
 [[0 1 1 0]
 [1 0 1 1]
 [1 1 0 1]
 [0 1 1 0]]


In [3]:
## Load a mesh in OFF format
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data","bunny.off"))

## Print the vertices and faces matrices 
print("Vertices: ", len(v))
print("Faces: ", len(f))

mp.plot(v,f)

Vertices:  3485
Faces:  6966


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [4]:
# Visualize Gaussian curvature
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data", "bumpy.off"))
k = igl.gaussian_curvature(v, f)
mp.plot(v, f, k)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [5]:
# Visualize gradients
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data", "cheburashka.off"))
u = igl.read_dmat(os.path.join(root_folder, "data", "cheburashka-scalar.dmat"))

g = igl.grad(v, f)
gu = g.dot(u).reshape(f.shape, order="F")

gu_mag = np.linalg.norm(gu, axis=1)
p = mp.plot(v, f, u, shading={"wireframe":False}, return_plot=True)

max_size = igl.avg_edge_length(v, f) / np.mean(gu_mag)
bc = igl.barycenter(v, f)
bcn = bc + max_size * gu
p.add_lines(bc, bcn, shading={"line_color": "black"});

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.4999999…

## Assignment

Change the code below to visualize the mean curvature normal at each vertex as a line, similar as in the gradient example above.

In [6]:
# Visualize mean curvature
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data", "bumpy.off"))
l = igl.cotmatrix(v, f)
m = igl.massmatrix(v, f, igl.MASSMATRIX_TYPE_VORONOI)

minv = sp.sparse.diags(1 / m.diagonal())

hn = -minv.dot(l.dot(v))
h = np.linalg.norm(hn, axis=1)
p = mp.plot(v, f, h, shading={"wireframe": False}, return_plot=True)

p.add_lines(v, v + hn, shading={"line_color": "black"})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

1